{% set name = "postgrest" %}
{% set version = "2.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73fcf2acfc0724702c0487224e3a1fdb888f7bfd9644eeb225a94d91be0920f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build >=0.8.3,<0.9.0
  run:
    - python >={{ python_min }}
    - deprecation >=2.1.0
    - httpx >=0.26.0,<0.28
    - pydantic >=1.9.0,<3
    - strenum >=0.4.9
    - yarl >=1.20.1

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - postgrest

about:
  home: https://github.com/supabase/supabase-py/tree/main/src/postgrest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PostgREST client for Python. This library provides an ORM interface to PostgREST
  description: PostgREST client for Python. This library provides an ORM interface to PostgREST

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
