{% set name = "postgrest" %}
{% set version = "0.16.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 779e20bd34f3c14e1e99129407612f85d7bb1d80b5cee2f54e50194b4488c658

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - deprecation >=2.1.0
    - httpx >=0.24.0,<0.26
    - pydantic >=1.9.0,<3
    - strenum >=0.4.9

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - postgrest

about:
  home: https://github.com/supabase-community/postgrest-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PostgREST client for Python. This library provides an ORM interface to PostgREST
  description: |
    PostgREST client for Python. This library provides an ORM interface to PostgREST

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
