{% set name = "postgrest" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d6556dadfd8392147d98aad097fe7bf0196602e28a58eee5e9bde4390bb573f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - deprecation >=2.1.0
    - httpx >=0.26.0,<0.28
    - pydantic >=1.9.0,<3
    - strenum >=0.4.9

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - postgrest

about:
  home: https://github.com/supabase-community/postgrest-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PostgREST client for Python. This library provides an ORM interface to PostgREST
  description: |
    PostgREST client for Python. This library provides an ORM interface to PostgREST

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
