{% set name = "postgrest" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a66714e21219e135e744eaf61031b28e2a11f7c4fe40bf60cb8f6d8b68c7e12b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - deprecation >=2.1.0
    - httpx >=0.26.0,<0.28
    - pydantic >=1.9.0,<3
    - strenum >=0.4.9

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - postgrest

about:
  home: https://github.com/supabase-community/postgrest-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PostgREST client for Python. This library provides an ORM interface to PostgREST
  description: |
    PostgREST client for Python. This library provides an ORM interface to PostgREST

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
